list_dinner = ['Raj','Mamatha','Vritika','Neehal']
print(f'you are invited to dinner {list_dinner[0].upper()}')
print(f'you are invited to dinner {list_dinner[1].upper()}')
print(f'you are invited to dinner {list_dinner[2].upper()}')
print(f'you are invited to dinner {list_dinner[-1].upper()}')
print(f'I cannot come to dinner {list_dinner.pop()}')
print(list_dinner)
print(f'add a new guest {list_dinner.insert(3,'Sudha')}')
print(f'add a new guest {list_dinner.insert(4,'Neehal')}')
print(f'add a new guest {list_dinner.append('Rushil')}')
print(list_dinner)
print(f'no space for more guest {list_dinner.pop(5)}')
print(f'no space for more guest {list_dinner.pop(4)}')
print(f'no space for more guest {list_dinner.pop(3)}')
print(f' no space for more guest {list_dinner.pop(2)}')
print(list_dinner)
del list_dinner[0]
list_dinner.remove('Mamatha')
print(list_dinner)