name: My first Workflow

on:
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
      - name: Welcome message
        run: echo "My first Github Actions job"

      - name: List files
        run: ls
